name: Update US Unemployment Map

on:
  schedule:
    - cron: "0 12 * * *"   # daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run update script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python update_page.py \
            --svg us-map-template.svg \
            --html index.html \
            --seasonal SA

      - name: Commit & push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore: update map from FRED [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
