name: Build unemployment map and update page

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 9 * * 1"   # every Monday 09:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Build map into index.html
        run: |
          python update_page.py \
            --svg us-map-template.svg \
            --html index.html \
            --seasonal SA
          git status --porcelain

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html us-map-template.svg || true
            git commit -m "ci: refresh unemployment map from FRED"
            git push
          else
            echo "No changes."
          fi
